PRODUCCION_APLAZALOH_QUERY = """
DECLARE @FECHA DATE = CAST(GETDATE() AS DATE);
DECLARE @META_BASE DECIMAL(18,2) = 260869.57;
DECLARE @META_DIA DECIMAL(18,2);

DECLARE @INICIO_MES DATE = DATEFROMPARTS(YEAR(@FECHA), MONTH(@FECHA), 1);
DECLARE @INICIO_MES_SIGUIENTE DATE = DATEADD(MONTH, 1, @INICIO_MES);

SET @META_DIA =
    CAST(
        CASE
            WHEN DATEDIFF(DAY, '19000106', @FECHA) % 7 = 0 THEN @META_BASE / 2
            ELSE @META_BASE
        END
    AS DECIMAL(18,2));

WITH base_mes AS (
    SELECT
        ISNULL(Q_MONTO_VENTA, 0) AS Q_MONTO_VENTA,
        ISNULL(Q_MONTO_VENTA_FLG2, 0) AS Q_MONTO_VENTA_FLG2,
        ISNULL(Q_MONTO_VENTA_FLG6, 0) AS Q_MONTO_VENTA_FLG6
    FROM ZRP_PRODUCCION_GESTOR_OH_APLAZALOH
    WHERE FECHA >= @INICIO_MES
      AND FECHA < @INICIO_MES_SIGUIENTE
),

base_dia AS (
    SELECT
        HORA,
        ISNULL(Q_VENTAS, 0) AS Q_VENTAS,
        ISNULL(Q_MONTO_VENTA, 0) AS Q_MONTO_VENTA,
        ISNULL(Q_VENTAS_FLG2, 0) AS Q_VENTAS_FLG2,
        ISNULL(Q_MONTO_VENTA_FLG2, 0) AS Q_MONTO_VENTA_FLG2,
        ISNULL(Q_VENTAS_FLG6, 0) AS Q_VENTAS_FLG6,
        ISNULL(Q_MONTO_VENTA_FLG6, 0) AS Q_MONTO_VENTA_FLG6
    FROM ZRP_PRODUCCION_GESTOR_OH_APLAZALOH
    WHERE FECHA = @FECHA
),

produccion_hora AS (
    SELECT
        HORA,
        SUM(Q_MONTO_VENTA) AS MONTO_HORA
    FROM base_dia
    GROUP BY HORA
),

resumen_mes AS (
    SELECT
        SUM(Q_MONTO_VENTA) AS TOTAL_B_MES,
        SUM(Q_MONTO_VENTA_FLG2) + SUM(Q_MONTO_VENTA_FLG6) * 0.8 AS TOTAL_N_MES
    FROM base_mes
),

resumen_dia AS (
    SELECT
        SUM(Q_MONTO_VENTA) AS TOTAL_DIA,
        SUM(Q_MONTO_VENTA_FLG2) AS MONTO_FLG2_DIA,
        SUM(Q_MONTO_VENTA_FLG6) AS MONTO_FLG6_DIA,
        SUM(Q_VENTAS) AS CANTIDAD_TOTAL_DIA,
        SUM(Q_VENTAS_FLG2) AS CANTIDAD_FLG2_DIA,
        SUM(Q_VENTAS_FLG6) AS CANTIDAD_FLG6_DIA,
        SUM(Q_MONTO_VENTA_FLG2) + SUM(Q_MONTO_VENTA_FLG6) * 0.8 AS TOTAL_N_DIA
    FROM base_dia
)

SELECT
    ph.HORA,
    ph.MONTO_HORA,

    rm.TOTAL_B_MES,
    rm.TOTAL_N_MES,

    rd.TOTAL_DIA,
    rd.TOTAL_N_DIA,
    rd.MONTO_FLG2_DIA,
    rd.MONTO_FLG6_DIA,
    rd.CANTIDAD_TOTAL_DIA,
    rd.CANTIDAD_FLG2_DIA,
    rd.CANTIDAD_FLG6_DIA,

    @META_DIA AS META_DIA,

    CAST(rd.TOTAL_N_DIA / NULLIF(@META_DIA, 0) AS DECIMAL(10,4)) AS CUMPLIMIENTO_DIA,
    CAST(rd.TOTAL_N_DIA / NULLIF(@META_DIA, 0) * 100 AS DECIMAL(10,2)) AS CUMPLIMIENTO_DIA_PCT

FROM produccion_hora ph
CROSS JOIN resumen_mes rm
CROSS JOIN resumen_dia rd
ORDER BY TRY_CONVERT(INT, ph.HORA) ASC;
"""


CONSOLIDADO_MES_QUERY = """
DECLARE @FECHA DATE = CAST(GETDATE() AS DATE);
DECLARE @INICIO_MES DATE = DATEFROMPARTS(YEAR(@FECHA), MONTH(@FECHA), 1);
DECLARE @INICIO_MES_SIGUIENTE DATE = DATEADD(MONTH, 1, @INICIO_MES);

SELECT
    FECHA,
    SUM(ISNULL(Q_MONTO_VENTA, 0)) AS TOTAL_DIA
FROM ZRP_PRODUCCION_GESTOR_OH_APLAZALOH
WHERE FECHA >= @INICIO_MES
  AND FECHA < @INICIO_MES_SIGUIENTE
GROUP BY FECHA
ORDER BY FECHA ASC;
"""
